#!/usr/bin/env php 

<?php

use Morse\MorseCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Application('Morse', 1.0);

$app->add(new MorseCommand);

$app->run();
